enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"
included-patches = "'Change start page' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom double tap length' 'Custom package name' 'GmsCore support' 'Hide ads' 'MaterialYou' 'Return YouTube Dislike' 'Settings for YouTube' 'SponsorBlock' 'Video playback'"
exclusive-patches = true
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube
